CREATE TABLE costumer (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
   first_name VARCHAR(255) NOT NULL,
   last_name VARCHAR(255) NOT NULL,
   cpf VARCHAR(255) NOT NULL,
   email VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   zip_code VARCHAR(255) NOT NULL,
   street VARCHAR(255) NOT NULL,
   CONSTRAINT pk_costumer PRIMARY KEY (id)
);

ALTER TABLE costumer ADD CONSTRAINT uc_costumer_cpf UNIQUE (cpf);

ALTER TABLE costumer ADD CONSTRAINT uc_costumer_email UNIQUE (email);